# --------------------------------------------------
#  基本网站信息
# --------------------------------------------------
title: ALRCMt # 主站点标题（出现在浏览器选项卡和RSS中）
tagline: Here is personal website of ALRCMt.  ＃可选的短标语，某些布局使用
description: To be, or not to be, that is the question.

# TIP ── For local development you can comment out `url`
# and build with relative paths. In production you want this set.
# url: https://caihanlin.com

# --------------------------------------------------
# 作者 /个人资料数据
# --------------------------------------------------
owner:
  name: ALRCMt
  avatar: ALRCMt.jpg
  # 简历：梦想大，保持积极，努力工作并享受旅程。
  email: alrcmt86@outlook.com
  # cv: https://caihanlin.com/file/CV-HanlinCAI.pdf

  #社交网络链接在作者Bio侧边栏中使用。更新并根据需要删除。
  # twitter: lancecai2002
  github: ALRCMt
  # linkedin: hanlincai
  # scholar: https://scholar.google.com/citations?user=8igSoWgAAAAJ
  # researchgate: https://www.researchgate.net/profile/Hanlin-Cai
  zhihu: https://www.zhihu.com/people/alrcmt
  # xiaohongshu: 5c27848f0000000005030c6f
  bilibili: 483215864
  # facebook: caihanlin2002
  # instagram: lancecai2002
  # lastfm:
  # tumblr:

# --------------------------------------------------
#  搜索引擎验证和分析
# --------------------------------------------------
google_verify: "SkiyuGpJOKT74vv5GmXLvYXXDkXy4v8VWPtbelYz3Hs"
# bing_verify: ""    # https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
# google_analytics: "G-XXXXXXX"                                 # GA-4 property ID

# --------------------------------------------------
#  顶级导航栏
#  `external: true` 在新标签中打开链接。
# --------------------------------------------------
links:
  - title: About Me
    url: /
  - title: Publications
    url: /publications/
  - title: Awards
    url: /awards/
  - title: Hobbies
    url: /hobbies/
  - title: Blogs
    url: /blogs/
  - title: 中文
    url: /cn/

# --------------------------------------------------
#  构建和渲染选项
# --------------------------------------------------
timezone: Asia/Shanghai # IANA时区ID（中国/北京无效）
future: true # Render posts dated in the future
highlighter: rouge # 代码荧光笔；胭脂默认为mm
# markdown: kramdown             # jekyll默认；武力的不满意
# pygments: true                 # 旧式选项（Rouge取代此）

# --------------------------------------------------
#  永久链接结构
# --------------------------------------------------
permalink: /:categories/:title # e.g. /tech/my-post/

# --------------------------------------------------
#  Kramdown（Markdown Engine）设置
# --------------------------------------------------
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

  # coderay:
  #   coderay_line_numbers:
  #   coderay_line_numbers_start: 1
  #   coderay_tab_width: 4
  #   coderay_bold_every: 10
  #   coderay_css: class

# --------------------------------------------------
#  DISQUS评论系统
# --------------------------------------------------
disqus:
  shortname: lancecai

# include: [".htaccess"]
# exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "minimal-mistakes.sublime-project", "minimal-mistakes.sublime-workspace"]

# --------------------------------------------------
#  包括 /排除列表
# --------------------------------------------------
include: [".htaccess"] # 文件迫使构建中的内容
exclude: # 构建过程中忽略的文件夹/文件
  - "lib"
  - "config.rb"
  - "Capfile"
  - "config"
  - "log"
  - "Rakefile"
  - "Rakefile.rb"
  - "tmp"
  - "less"
  - "minimal-mistakes.sublime-project"
  - "minimal-mistakes.sublime-workspace"

# --------------------------------------------------
#  OPTIONAL PLUG-INS (uncomment once gems are added)
# --------------------------------------------------
plugins:
  - jekyll-feed # Auto-generate RSS feed
  - jekyll-sitemap # Auto-generate sitemap.xml
  - jekyll-seo-tag # Adds SEO meta tags & JSON-LD
#   - jekyll-picture-tag   # Responsive images & WebP/AVIF
# - jekyll-archives      # Year/month archive pages
